# src/main/resources/application.yml

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: user
      password: password

logging:
  level:
    org:
      springframework:
        security: INFO

jwt:
  secret: wMedjXRhB3mSsfzE4SNhKRzMBrAuAcM+NJpPqFCSFbY=
  expirationMs: 3600000 # 1 hour
